### ISSUE TITLE
There is no timer, there is no pause for sending comments

### ISSUE THREAD

**Issue by vassilevev** [Delafault/TelegramAutoCommentor#1]
It will probably be useful to add a timer. Here's the code:

import asyncio

async def handle_new_posts(event):
    print("Создан новый пост. Комментирую...")
    message = event.message
    comment_text = random.choice(texts_commented)
    
    for entity in channel_entities:
        if entity.id == message.peer_id.channel_id:
            if not message.out and message.id not in commented_messages[entity.id]:
                try:
                    await asyncio.sleep(60) # Ожидание 60 секунд
                    await client.send_message(entity=entity, message=comment_text, comment_to=message)
                    gd_print("Созданный пост успешно прокомментирован.")
                    commented_messages[entity.id].add(message.id)
                except Exception as e:
                    bd_print(f"Возникла ошибка при комментировании записи: {e}")

**Comment by Delafault** [comment]
Oh, thanks! Actually the script's job is to react to the post as quickly as possible to send the first comment (which, of course, he sometimes doesn't do a very good job with), but you can always edit the script to suit your needs.
